name: Build and Deploy Wedding Photo Site to GitHub Pages

on:
  push:
    branches: [main]  # or your default branch

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env: 
      DRY_RUN: ${{ secrets.DRY_RUN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Pull image urls from gh secrets
        run: |
          mkdir -p build/config
          mkdir -p build/data
          curl -L "$CEREMONY" -o build/data/ceremony.json
          curl -L "$DETAILS" -o build/data/details.json
          curl -L "$FILM_SCANS" -o build/data/film_scans.json
          curl -L "$GETTING_READY" -o build/data/getting_ready.json
          curl -L "$GROUP_FAMILY" -o build/data/group_family.json
          curl -L "$RECEPTION" -o build/data/reception.json
          curl -L "$THE_COUPLE" -o build/data/the_couple.json
        env:
          CEREMONY: ${{ secrets.CEREMONY }}
          DETAILS: ${{ secrets.DETAILS }}
          FILM_SCANS: ${{ secrets.FILM_SCANS }}
          GETTING_READY: ${{ secrets.GETTING_READY }}
          GROUP_FAMILY: ${{ secrets.GROUP_FAMILY }}
          RECEPTION: ${{ secrets.RECEPTION }}
          THE_COUPLE: ${{ secrets.THE_COUPLE }}

      - name: Copy site files
        working-directory: ${{ github.workspace }}
        run: |
          mkdir -p build/js
          mkdir -p build/css
          cp index.html build/
          cp -r js/* build/js/
          cp -r css/* build/css/

      - name: Replace IMAGE_BASE_URL placeholder
        env:
          IMAGE_BASE_URL: ${{ secrets.IMAGE_BASE_URL }}
        run: |
          sed -i "s|__IMAGE_BASE_URL__|\"$IMAGE_BASE_URL\"|g" build/index.html
          echo $IMAGE_BASE_URL

      - name: Deploy to GitHub Pages
        if: env.DRY_RUN != 'true'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
